modLoader = "javafml"
loaderVersion = "[31,)"

authors = "vultorio, koda"
license = "Unlicense"
issueTrackerURL = "https://github.com/chylex/Minecraft-Window-Title/issues"

[[mods]]
modId = "amc"
version = "1.1.0"
displayName = "AMC"
displayURL = "https://github.com/chylex/Minecraft-Window-Title"

[[dependencies.amc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.amc]]
modId = "forge"
mandatory = true
versionRange = "[31,)"
ordering = "NONE"
side = "CLIENT"